const screenTags = [
  'analogue-pocket',
  'rg-rotate',
  'rg477v',
  'rg-ds',
  'rg476h',
  'rg477m',
  'rg35xx',
  'rg34xx',
  'rg40xx',
  'rg28xx',
  'rg557',
  'rg351p',
  'rg405m',
  'rg406v',
  'rg-cube',
  'rg503',
  'rg556',
  'win600',
  'rg552',
  'pocket-micro',
  'pocket-s',
  'pocket-evo',
  'pocket-dmg',
  'thor-top',
  'thor-bottom',
  'odin-3',
  'odin-2-portal',
  'odin-2',
  'funkey-s',
  'fp-rpp',
  'kt-r1',
  'magicx-zero-40',
  'miyoo-mini',
  'miyoo-mini-v4',
  'miyoo-mini-flip',
  'miyoo-mini-plus',
  'pk-rgb30',
  'pk-rgb10-max',
  'rp-nova',
  'rp-6',
  'rp-flip-2',
  'rp-classic',
  'rp-5',
  'rp-4',
  'rp-mini',
  'rp-3',
  'sjgam-m17',
  'trimui-brick-pro',
  'trimui-brick',
  'trimui-smart-pro',
  'trimui-smart',
  'steam-deck',
] as const
export type ScreenTag = (typeof screenTags)[number]

export const screenManufacturers = [
  'Analogue',
  'Anbernic',
  'Ayaneo',
  'AYN',
  'FunKey',
  'FunnyPlaying',
  'KT Pocket',
  'MagicX',
  'Miyoo',
  'PowKiddy',
  'Retroid Pocket',
  'SJGAM',
  'TrimUI',
  'Valve',
] as const
export type ScreenManufacturer = (typeof screenManufacturers)[number]

export const screenRatioTypes = ['4:3', '16:9', '3:2', '1:1', 'Other'] as const
export type ScreenRatioType = (typeof screenRatioTypes)[number]

export type ScreensByTag = Record<ScreenTag, Screen>

export interface Screen {
  tag: ScreenTag
  manufacturer: ScreenManufacturer
  name: string
  resX: number
  resY: number
  sizeInches: number
  ratioType: ScreenRatioType
  ratioX: number
  ratioY: number
}
export const screensByTag: Record<ScreenTag, Screen> = {
  'analogue-pocket': {
    tag: 'analogue-pocket',
    manufacturer: 'Analogue',
    name: 'Pocket',
    resX: 1600,
    resY: 1440,
    sizeInches: 3.5,
    ratioType: 'Other',
    ratioX: 10,
    ratioY: 9,
  },
  'rg-rotate': {
    tag: 'rg-rotate',
    manufacturer: 'Anbernic',
    name: 'RG Rotate',
    resX: 720,
    resY: 720,
    sizeInches: 3.5,
    ratioType: '1:1',
    ratioX: 1,
    ratioY: 1,
  },
  'rg-ds': {
    tag: 'rg-ds',
    manufacturer: 'Anbernic',
    name: 'RG DS',
    resX: 640,
    resY: 480,
    sizeInches: 4,
    ratioType: '4:3',
    ratioX: 4,
    ratioY: 3,
  },
  rg477v: {
    tag: 'rg477v',
    manufacturer: 'Anbernic',
    name: 'RG 477V',
    resX: 1280,
    resY: 960,
    sizeInches: 4.7,
    ratioType: '4:3',
    ratioX: 4,
    ratioY: 3,
  },
  rg476h: {
    tag: 'rg476h',
    manufacturer: 'Anbernic',
    name: 'RG 476H',
    resX: 1280,
    resY: 960,
    sizeInches: 4.7,
    ratioType: '4:3',
    ratioX: 4,
    ratioY: 3,
  },
  rg477m: {
    tag: 'rg477m',
    manufacturer: 'Anbernic',
    name: 'RG 477M',
    resX: 1280,
    resY: 960,
    sizeInches: 4.7,
    ratioType: '4:3',
    ratioX: 4,
    ratioY: 3,
  },
  rg35xx: {
    tag: 'rg35xx',
    manufacturer: 'Anbernic',
    name: 'RG 35XX (all models)',
    resX: 640,
    resY: 480,
    sizeInches: 3.5,
    ratioType: '4:3',
    ratioX: 4,
    ratioY: 3,
  },
  rg34xx: {
    tag: 'rg34xx',
    manufacturer: 'Anbernic',
    name: 'RG 34XX (all models)',
    resX: 720,
    resY: 480,
    sizeInches: 3.4,
    ratioType: '3:2',
    ratioX: 3,
    ratioY: 2,
  },
  rg40xx: {
    tag: 'rg40xx',
    manufacturer: 'Anbernic',
    name: 'RG 40XX (all models)',
    resX: 640,
    resY: 480,
    sizeInches: 4,
    ratioType: '4:3',
    ratioX: 4,
    ratioY: 3,
  },
  rg28xx: {
    tag: 'rg28xx',
    manufacturer: 'Anbernic',
    name: 'RG 28XX',
    resX: 640,
    resY: 480,
    sizeInches: 2.8,
    ratioType: '4:3',
    ratioX: 4,
    ratioY: 3,
  },
  rg557: {
    tag: 'rg557',
    manufacturer: 'Anbernic',
    name: 'RG 577',
    resX: 1920,
    resY: 1080,
    sizeInches: 5.48,
    ratioType: '16:9',
    ratioX: 16,
    ratioY: 9,
  },
  rg351p: {
    tag: 'rg351p',
    manufacturer: 'Anbernic',
    name: 'RG 351P',
    resX: 480,
    resY: 320,
    sizeInches: 3.5,
    ratioType: '3:2',
    ratioX: 3,
    ratioY: 2,
  },
  rg406v: {
    tag: 'rg406v',
    manufacturer: 'Anbernic',
    name: 'RG 406V',
    resX: 960,
    resY: 720,
    sizeInches: 4,
    ratioType: '4:3',
    ratioX: 4,
    ratioY: 3,
  },
  'rg-cube': {
    tag: 'rg-cube',
    manufacturer: 'Anbernic',
    name: 'RG Cube(XX)',
    resX: 720,
    resY: 720,
    sizeInches: 3.95,
    ratioType: '1:1',
    ratioX: 1,
    ratioY: 1,
  },
  rg556: {
    tag: 'rg556',
    manufacturer: 'Anbernic',
    name: 'RG 556',
    resX: 1920,
    resY: 1080,
    sizeInches: 5.48,
    ratioType: '16:9',
    ratioX: 16,
    ratioY: 9,
  },
  rg405m: {
    tag: 'rg405m',
    manufacturer: 'Anbernic',
    name: 'RG 405(M & V)',
    resX: 640,
    resY: 480,
    sizeInches: 4,
    ratioType: '4:3',
    ratioX: 4,
    ratioY: 3,
  },
  rg503: {
    tag: 'rg503',
    manufacturer: 'Anbernic',
    name: 'RG 503',
    resX: 960,
    resY: 544,
    sizeInches: 5,
    ratioType: '16:9',
    ratioX: 16,
    ratioY: 9,
  },
  win600: {
    tag: 'win600',
    manufacturer: 'Anbernic',
    name: 'WIN600',
    resX: 1280,
    resY: 720,
    sizeInches: 5.94,
    ratioType: '16:9',
    ratioX: 16,
    ratioY: 9,
  },
  rg552: {
    tag: 'rg552',
    manufacturer: 'Anbernic',
    name: 'RG 552',
    resX: 1920,
    resY: 1152,
    sizeInches: 5.36,
    ratioType: 'Other',
    ratioX: 5,
    ratioY: 3,
  },
  'pocket-micro': {
    tag: 'pocket-micro',
    manufacturer: 'Ayaneo',
    name: 'Pocket Micro',
    resX: 960,
    resY: 640,
    sizeInches: 3.5,
    ratioType: '3:2',
    ratioX: 3,
    ratioY: 2,
  },
  'pocket-s': {
    tag: 'pocket-s',
    manufacturer: 'Ayaneo',
    name: 'Pocket S',
    resX: 2560,
    resY: 1440,
    sizeInches: 6,
    ratioType: '16:9',
    ratioX: 16,
    ratioY: 9,
  },
  'pocket-evo': {
    tag: 'pocket-evo',
    manufacturer: 'Ayaneo',
    name: 'Pocket EVO',
    resX: 1920,
    resY: 1080,
    sizeInches: 7,
    ratioType: '16:9',
    ratioX: 16,
    ratioY: 9,
  },
  'pocket-dmg': {
    tag: 'pocket-dmg',
    manufacturer: 'Ayaneo',
    name: 'Pocket DMG',
    resX: 1240,
    resY: 1080,
    sizeInches: 3.92,
    ratioType: 'Other',
    ratioX: 31,
    ratioY: 27,
  },
  'thor-top': {
    tag: 'thor-top',
    manufacturer: 'AYN',
    name: 'Thor (top)',
    resX: 1920,
    resY: 1080,
    sizeInches: 6,
    ratioType: '16:9',
    ratioX: 16,
    ratioY: 9,
  },
  'thor-bottom': {
    tag: 'thor-bottom',
    manufacturer: 'AYN',
    name: 'Thor (bottom)',
    resX: 1240,
    resY: 1080,
    sizeInches: 3.92,
    ratioType: 'Other',
    ratioX: 31,
    ratioY: 27,
  },
  'odin-3': {
    tag: 'odin-3',
    manufacturer: 'AYN',
    name: 'Odin 3',
    resX: 1920,
    resY: 1080,
    sizeInches: 6,
    ratioType: '16:9',
    ratioX: 16,
    ratioY: 9,
  },
  'odin-2-portal': {
    tag: 'odin-2-portal',
    manufacturer: 'AYN',
    name: 'Odin 2 Portal',
    resX: 1920,
    resY: 1080,
    sizeInches: 7,
    ratioType: '16:9',
    ratioX: 16,
    ratioY: 9,
  },
  'odin-2': {
    tag: 'odin-2',
    manufacturer: 'AYN',
    name: 'Odin 2',
    resX: 1920,
    resY: 1080,
    sizeInches: 6,
    ratioType: '16:9',
    ratioX: 16,
    ratioY: 9,
  },
  'funkey-s': {
    tag: 'funkey-s',
    manufacturer: 'FunKey',
    name: 'S',
    resX: 240,
    resY: 240,
    sizeInches: 1.54,
    ratioType: '1:1',
    ratioX: 1,
    ratioY: 1,
  },
  'fp-rpp': {
    tag: 'fp-rpp',
    manufacturer: 'FunnyPlaying',
    name: 'Retro Pixel Pocket',
    resX: 720,
    resY: 720,
    sizeInches: 3.1,
    ratioType: '1:1',
    ratioX: 1,
    ratioY: 1,
  },
  'kt-r1': {
    tag: 'kt-r1',
    manufacturer: 'KT Pocket',
    name: 'KT-R1',
    resX: 1620,
    resY: 1080,
    sizeInches: 4.5,
    ratioType: '3:2',
    ratioX: 3,
    ratioY: 2,
  },
  'magicx-zero-40': {
    tag: 'magicx-zero-40',
    manufacturer: 'MagicX',
    name: 'Zero 40',
    resX: 480,
    resY: 800,
    sizeInches: 4,
    ratioType: 'Other',
    ratioX: 3,
    ratioY: 5,
  },
  'miyoo-mini': {
    tag: 'miyoo-mini',
    manufacturer: 'Miyoo',
    name: 'Mini',
    resX: 640,
    resY: 480,
    sizeInches: 2.8,
    ratioType: '4:3',
    ratioX: 4,
    ratioY: 3,
  },
  'miyoo-mini-v4': {
    tag: 'miyoo-mini-v4',
    manufacturer: 'Miyoo',
    name: 'Mini (v4)',
    resX: 752,
    resY: 560,
    sizeInches: 2.8,
    ratioType: '4:3',
    ratioX: 4,
    ratioY: 3,
  },
  'miyoo-mini-flip': {
    tag: 'miyoo-mini-flip',
    manufacturer: 'Miyoo',
    name: 'Mini Flip',
    resX: 752,
    resY: 560,
    sizeInches: 2.8,
    ratioType: '4:3',
    ratioX: 4,
    ratioY: 3,
  },
  'miyoo-mini-plus': {
    tag: 'miyoo-mini-plus',
    manufacturer: 'Miyoo',
    name: 'Mini Plus',
    resX: 640,
    resY: 480,
    sizeInches: 3.5,
    ratioType: '4:3',
    ratioX: 4,
    ratioY: 3,
  },
  'pk-rgb30': {
    tag: 'pk-rgb30',
    manufacturer: 'PowKiddy',
    name: 'RGB30',
    resX: 720,
    resY: 720,
    sizeInches: 4,
    ratioType: '1:1',
    ratioX: 1,
    ratioY: 1,
  },
  'pk-rgb10-max': {
    tag: 'pk-rgb10-max',
    manufacturer: 'PowKiddy',
    name: 'RGB10 Max',
    resX: 854,
    resY: 480,
    sizeInches: 5,
    ratioType: '16:9',
    ratioX: 16,
    ratioY: 9,
  },
  'rp-nova': {
    tag: 'rp-nova',
    manufacturer: 'Retroid Pocket',
    name: 'Nova',
    resX: 1280,
    resY: 960,
    sizeInches: 4.5,
    ratioType: '4:3',
    ratioX: 4,
    ratioY: 3,
  },
  'rp-6': {
    tag: 'rp-6',
    manufacturer: 'Retroid Pocket',
    name: '6',
    resX: 1920,
    resY: 1080,
    sizeInches: 5.5,
    ratioType: '16:9',
    ratioX: 16,
    ratioY: 9,
  },
  'rp-flip-2': {
    tag: 'rp-flip-2',
    manufacturer: 'Retroid Pocket',
    name: 'Flip 2',
    resX: 1920,
    resY: 1080,
    sizeInches: 5.5,
    ratioType: '16:9',
    ratioX: 16,
    ratioY: 9,
  },
  'rp-classic': {
    tag: 'rp-classic',
    manufacturer: 'Retroid Pocket',
    name: 'Classic',
    resX: 1240,
    resY: 1080,
    sizeInches: 3.92,
    ratioType: 'Other',
    ratioX: 31,
    ratioY: 27,
  },
  'rp-5': {
    tag: 'rp-5',
    manufacturer: 'Retroid Pocket',
    name: '5',
    resX: 1920,
    resY: 1080,
    sizeInches: 5.5,
    ratioType: '16:9',
    ratioX: 16,
    ratioY: 9,
  },
  'rp-4': {
    tag: 'rp-4',
    manufacturer: 'Retroid Pocket',
    name: '4/4 Pro',
    resX: 1334,
    resY: 750,
    sizeInches: 4.7,
    ratioType: 'Other',
    ratioX: 667,
    ratioY: 375,
  },
  'rp-mini': {
    tag: 'rp-mini',
    manufacturer: 'Retroid Pocket',
    name: 'Mini',
    resX: 1280,
    resY: 960,
    sizeInches: 3.7,
    ratioType: '4:3',
    ratioX: 4,
    ratioY: 3,
  },
  'rp-3': {
    tag: 'rp-3',
    manufacturer: 'Retroid Pocket',
    name: '3',
    resX: 1334,
    resY: 750,
    sizeInches: 4.7,
    ratioType: '16:9',
    ratioX: 16,
    ratioY: 9,
  },
  'sjgam-m17': {
    tag: 'sjgam-m17',
    manufacturer: 'SJGAM',
    name: 'M17',
    resX: 480,
    resY: 272,
    sizeInches: 4.3,
    ratioType: '16:9',
    ratioX: 16,
    ratioY: 9,
  },
  'trimui-brick-pro': {
    tag: 'trimui-brick-pro',
    manufacturer: 'TrimUI',
    name: 'Brick (Hammer) PRO (U)',
    resX: 1024,
    resY: 768,
    sizeInches: 3.95,
    ratioType: '4:3',
    ratioX: 4,
    ratioY: 3,
  },
  'trimui-brick': {
    tag: 'trimui-brick',
    manufacturer: 'TrimUI',
    name: 'Brick (Hammer)',
    resX: 1024,
    resY: 768,
    sizeInches: 3.2,
    ratioType: '4:3',
    ratioX: 4,
    ratioY: 3,
  },
  'trimui-smart-pro': {
    tag: 'trimui-smart-pro',
    manufacturer: 'TrimUI',
    name: 'Smart Pro',
    resX: 1280,
    resY: 720,
    sizeInches: 4.96,
    ratioType: '16:9',
    ratioX: 16,
    ratioY: 9,
  },
  'trimui-smart': {
    tag: 'trimui-smart',
    manufacturer: 'TrimUI',
    name: 'Smart',
    resX: 320,
    resY: 240,
    sizeInches: 2.4,
    ratioType: '4:3',
    ratioX: 4,
    ratioY: 3,
  },
  'steam-deck': {
    tag: 'steam-deck',
    manufacturer: 'Valve',
    name: 'Steam Deck',
    resX: 1280,
    resY: 800,
    sizeInches: 7,
    ratioType: 'Other',
    ratioX: 16,
    ratioY: 10,
  },
}

export const screenGroupingOptions = ['Aspect ratio', 'Manufacturer', 'Resolution'] as const
export type ScreenGroupingOption = (typeof screenGroupingOptions)[number]

export type ScreensByManufacturer = Record<ScreenManufacturer, Screen[]>
export const screensByManufacturer: ScreensByManufacturer = screenManufacturers.reduce(
  (screensBy, manufacturer) => ({ ...screensBy, [manufacturer]: [] }),
  {} as ScreensByManufacturer,
)

export type ScreensByRatio = Record<ScreenRatioType, Screen[]>
export const screensByRatio: ScreensByRatio = screenRatioTypes.reduce(
  (screensBy, ratio) => ({ ...screensBy, [ratio]: [] }),
  {} as ScreensByRatio,
)

export type ScreensByRes = Record<string, Screen[]>
export const screensByRes: ScreensByRes = {} as ScreensByRes

//
;(Object.keys(screensByTag) as ScreenTag[]).forEach((tag) => {
  const screen = screensByTag[tag]
  screensByManufacturer[screen.manufacturer].push(screen)
  screensByRatio[screen.ratioType].push(screen)

  const res = screen.resX + 'x' + screen.resY
  if (screensByRes.hasOwnProperty(res)) {
    screensByRes[res].push(screen)
  } else {
    screensByRes[res] = [screen]
  }
})
