export const screenTags = [
  'analogue-pocket',
  'rg34xx',
  'rg351',
  'rg280m',
  'rg35xx',
  'rg405m',
  'rg406v',
  'rg503',
  'rg556',
  'win600',
  'rg552',
  'pocket-micro',
  'pocket-s',
  'pocket-evo',
  'pocket-dmg',
  'funkey-s',
  'fp-rpp',
  'kt-r1',
  'magicx-zero-40',
  'miyoo-mini',
  'miyoo-mini-v4',
  'miyoo-mini-flip',
  'miyoo-mini-plus',
  'pk-rgb30',
  'pk-rgb10-max',
  'rp-mini',
  'rp-3',
  'sjgam-m17',
  'trimui-smart',
  'trimui-brick',
  'trimui-smart-pro',
  'steam-deck',
] as const
export type ScreenTag = (typeof screenTags)[number]

export const screenManufacturers = [
  'Analogue',
  'Anbernic',
  'Ayaneo',
  'FunKey',
  'FunnyPlaying',
  'KT Pocket',
  'MagicX',
  'Miyoo',
  'PowKiddy',
  'Powkiddy',
  'Retroid Pocket',
  'SJGAM',
  'TrimUI',
  'Valve',
] as const
export type ScreenManufacturer = (typeof screenManufacturers)[number]

export const screenRatioTypes = ['4:3', '16:9', '3:2', '1:1', 'Other'] as const
export type ScreenRatioType = (typeof screenRatioTypes)[number]

export interface Screen {
  tag: ScreenTag
  manufacturer: ScreenManufacturer
  name: string
  resX: number
  resY: number
  sizeInches: number
  ratioType: ScreenRatioType
  ratioX: number
  ratioY: number
}
export const screens: Screen[] = [
  {
    tag: 'analogue-pocket',
    manufacturer: 'Analogue',
    name: 'Pocket',
    resX: 1600,
    resY: 1440,
    sizeInches: 3.5,
    ratioType: 'Other',
    ratioX: 10,
    ratioY: 9,
  },
  {
    tag: 'rg35xx',
    manufacturer: 'Anbernic',
    name: 'RG35XX',
    resX: 640,
    resY: 480,
    sizeInches: 3.5,
    ratioType: '4:3',
    ratioX: 4,
    ratioY: 3,
  },
  {
    tag: 'rg34xx',
    manufacturer: 'Anbernic',
    name: 'RG34XX',
    resX: 720,
    resY: 480,
    sizeInches: 3.4,
    ratioType: '3:2',
    ratioX: 3,
    ratioY: 2,
  },
  {
    tag: 'rg351',
    manufacturer: 'Anbernic',
    name: 'RG351',
    resX: 480,
    resY: 320,
    sizeInches: 3.5,
    ratioType: '3:2',
    ratioX: 3,
    ratioY: 2,
  },
  {
    tag: 'rg280m',
    manufacturer: 'Anbernic',
    name: 'RG280M',
    resX: 320,
    resY: 240,
    sizeInches: 2.8,
    ratioType: '4:3',
    ratioX: 4,
    ratioY: 3,
  },
  {
    tag: 'rg405m',
    manufacturer: 'Anbernic',
    name: 'RG405M',
    resX: 640,
    resY: 480,
    sizeInches: 4,
    ratioType: '4:3',
    ratioX: 4,
    ratioY: 3,
  },
  {
    tag: 'rg406v',
    manufacturer: 'Anbernic',
    name: 'RG406V',
    resX: 960,
    resY: 720,
    sizeInches: 4,
    ratioType: '4:3',
    ratioX: 4,
    ratioY: 3,
  },
  {
    tag: 'rg503',
    manufacturer: 'Anbernic',
    name: 'RG503',
    resX: 960,
    resY: 544,
    sizeInches: 5,
    ratioType: '16:9',
    ratioX: 16,
    ratioY: 9,
  },
  {
    tag: 'rg556',
    manufacturer: 'Anbernic',
    name: 'RG556',
    resX: 1920,
    resY: 1080,
    sizeInches: 5.48,
    ratioType: '16:9',
    ratioX: 16,
    ratioY: 9,
  },
  {
    tag: 'win600',
    manufacturer: 'Anbernic',
    name: 'WIN600',
    resX: 1280,
    resY: 720,
    sizeInches: 5.94,
    ratioType: '16:9',
    ratioX: 16,
    ratioY: 9,
  },
  {
    tag: 'rg552',
    manufacturer: 'Anbernic',
    name: 'RG552',
    resX: 1920,
    resY: 1152,
    sizeInches: 5.36,
    ratioType: 'Other',
    ratioX: 5,
    ratioY: 3,
  },
  {
    tag: 'pocket-micro',
    manufacturer: 'Ayaneo',
    name: 'Pocket Micro',
    resX: 960,
    resY: 640,
    sizeInches: 3.5,
    ratioType: '3:2',
    ratioX: 3,
    ratioY: 2,
  },
  {
    tag: 'pocket-s',
    manufacturer: 'Ayaneo',
    name: 'Pocket S',
    resX: 2560,
    resY: 1440,
    sizeInches: 6,
    ratioType: '16:9',
    ratioX: 16,
    ratioY: 9,
  },
  {
    tag: 'pocket-evo',
    manufacturer: 'Ayaneo',
    name: 'Pocket EVO',
    resX: 1920,
    resY: 1080,
    sizeInches: 7,
    ratioType: '16:9',
    ratioX: 16,
    ratioY: 9,
  },
  {
    tag: 'pocket-dmg',
    manufacturer: 'Ayaneo',
    name: 'Pocket DMG',
    resX: 1240,
    resY: 1080,
    sizeInches: 3.92,
    ratioType: 'Other',
    ratioX: 8,
    ratioY: 7,
  },
  {
    tag: 'funkey-s',
    manufacturer: 'FunKey',
    name: 'S',
    resX: 240,
    resY: 240,
    sizeInches: 1.54,
    ratioType: '1:1',
    ratioX: 1,
    ratioY: 1,
  },
  {
    tag: 'fp-rpp',
    manufacturer: 'FunnyPlaying',
    name: 'Retro Pixel Pocket',
    resX: 720,
    resY: 720,
    sizeInches: 3.1,
    ratioType: '1:1',
    ratioX: 1,
    ratioY: 1,
  },
  {
    tag: 'kt-r1',
    manufacturer: 'KT Pocket',
    name: 'KT-R1',
    resX: 1620,
    resY: 1080,
    sizeInches: 4.5,
    ratioType: '3:2',
    ratioX: 3,
    ratioY: 2,
  },
  {
    tag: 'magicx-zero-40',
    manufacturer: 'MagicX',
    name: 'Zero 40',
    resX: 480,
    resY: 800,
    sizeInches: 4,
    ratioType: 'Other',
    ratioX: 3,
    ratioY: 5,
  },
  {
    tag: 'miyoo-mini',
    manufacturer: 'Miyoo',
    name: 'Mini',
    resX: 640,
    resY: 480,
    sizeInches: 2.8,
    ratioType: '4:3',
    ratioX: 4,
    ratioY: 3,
  },
  {
    tag: 'miyoo-mini-v4',
    manufacturer: 'Miyoo',
    name: 'Mini (v4)',
    resX: 752,
    resY: 560,
    sizeInches: 2.8,
    ratioType: '4:3',
    ratioX: 4,
    ratioY: 3,
  },
  {
    tag: 'miyoo-mini-flip',
    manufacturer: 'Miyoo',
    name: 'Mini Flip',
    resX: 752,
    resY: 560,
    sizeInches: 2.8,
    ratioType: '4:3',
    ratioX: 4,
    ratioY: 3,
  },
  {
    tag: 'miyoo-mini-plus',
    manufacturer: 'Miyoo',
    name: 'Mini Plus',
    resX: 640,
    resY: 480,
    sizeInches: 3.5,
    ratioType: '4:3',
    ratioX: 4,
    ratioY: 3,
  },
  {
    tag: 'pk-rgb30',
    manufacturer: 'Powkiddy',
    name: 'RGB30',
    resX: 720,
    resY: 720,
    sizeInches: 4,
    ratioType: '1:1',
    ratioX: 1,
    ratioY: 1,
  },
  {
    tag: 'pk-rgb10-max',
    manufacturer: 'PowKiddy',
    name: 'RGB10 Max',
    resX: 854,
    resY: 480,
    sizeInches: 5,
    ratioType: '16:9',
    ratioX: 16,
    ratioY: 9,
  },
  {
    tag: 'rp-mini',
    manufacturer: 'Retroid Pocket',
    name: 'Mini',
    resX: 1280,
    resY: 960,
    sizeInches: 3.7,
    ratioType: '4:3',
    ratioX: 4,
    ratioY: 3,
  },
  {
    tag: 'rp-3',
    manufacturer: 'Retroid Pocket',
    name: '3',
    resX: 1334,
    resY: 750,
    sizeInches: 4.7,
    ratioType: '16:9',
    ratioX: 16,
    ratioY: 9,
  },
  {
    tag: 'sjgam-m17',
    manufacturer: 'SJGAM',
    name: 'M17',
    resX: 480,
    resY: 272,
    sizeInches: 4.3,
    ratioType: '16:9',
    ratioX: 16,
    ratioY: 9,
  },
  {
    tag: 'trimui-brick',
    manufacturer: 'TrimUI',
    name: 'Brick',
    resX: 1024,
    resY: 768,
    sizeInches: 3.2,
    ratioType: '4:3',
    ratioX: 4,
    ratioY: 3,
  },
  {
    tag: 'trimui-smart-pro',
    manufacturer: 'TrimUI',
    name: 'Smart Pro',
    resX: 1280,
    resY: 720,
    sizeInches: 4.96,
    ratioType: '16:9',
    ratioX: 16,
    ratioY: 9,
  },
  {
    tag: 'trimui-smart',
    manufacturer: 'TrimUI',
    name: 'Smart',
    resX: 320,
    resY: 240,
    sizeInches: 2.4,
    ratioType: '4:3',
    ratioX: 4,
    ratioY: 3,
  },
  {
    tag: 'steam-deck',
    manufacturer: 'Valve',
    name: 'Steam Deck',
    resX: 1280,
    resY: 800,
    sizeInches: 7,
    ratioType: 'Other',
    ratioX: 16,
    ratioY: 10,
  },
  // {
  //   tag: '',
  //   manufacturer: '',
  //   name: '',
  //   resX: ,
  //   resY: ,
  //   sizeInches: ,
  //   ratioType: '',
  //   ratioX: ,
  //   ratioY: ,
  // },
]

export const screenGroupingOptions = ['ratioType', 'manufacturer'] as const
export type ScreenGroupingOption = (typeof screenGroupingOptions)[number]

export type ScreensByTag = Record<ScreenTag, Screen>
export const screensByTag: ScreensByTag = {} as ScreensByTag

export type ScreensByManufacturer = Record<ScreenManufacturer, Screen[]>
export const screensByManufacturer: ScreensByManufacturer = screenManufacturers.reduce(
  (screensBy, manufacturer) => ({ ...screensBy, [manufacturer]: [] }),
  {} as ScreensByManufacturer,
)

export type ScreensByRatio = Record<ScreenRatioType, Screen[]>
export const screensByRatio: ScreensByRatio = screenRatioTypes.reduce(
  (screensBy, ratio) => ({ ...screensBy, [ratio]: [] }),
  {} as ScreensByRatio,
)

screens.forEach((screen) => {
  screensByTag[screen.tag] = screen
  screensByManufacturer[screen.manufacturer].push(screen)
  screensByRatio[screen.ratioType].push(screen)
})

// console.log(
//   screens.toSorted((a, b) => a.manufacturer.localeCompare(b.manufacturer)).map((a) => a.tag)
// )
